# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import os
import sys
import glob
import yaml
from jinja2 import Template


TMPL = """# -*- coding: utf-8 -*-
# This file is generated by djconf. Local changes will be overwritten
{% for key, value in attrs -%}
{{ key }} = {{ value }}
{% endfor -%}
"""

def generate_settings(source_dir, output_filename, env='prod'):
    src = [(x, os.path.basename(x)) for x in glob.glob(os.path.join(source_dir, '*.yaml'))]
    src.sort(lambda a, b: cmp(a[1], b[1]))

    final_attrs = {}

    for path, _ in src:
        with open(path) as fp:
            data = yaml.load(fp)
            if not data:
                continue

            default = data.get('default', {})
            attrs = data.get(env, {})

            default.update(attrs)

            final_attrs.update(default)

    output = Template(TMPL).render({
        'attrs': final_attrs.items(),
    })

    if output_filename == '-':
        print(output)
    else:
        with open(output_filename, 'wb') as fp:
            fp.write(output)
